"""retrieval: guven kapisi, komsu-chunk baglami, baglam metni, top-k."""
import pytest
from sklearn.feature_extraction.text import TfidfVectorizer

import retrieval
from retrieval import (
    RETRIEVAL_MIN_SCORE, build_context, context_chunks, get_top_chunks,
    is_confident,
)

# Sentetik indeks: 3 chunk a.md, 2 chunk b.md; id'ler dosya sirasinda
ROWS = [
    (0, "a.md", "A0", "## A0\nlaminar boundary layer"),
    (1, "a.md", "A1", "## A1\nreynolds number scaling"),
    (2, "a.md", "A2", "## A2\nturbulent separation stall"),
    (3, "b.md", "B0", "## B0\nstatic stability trim"),
    (4, "b.md", "B1", "## B1\ndynamic stability damping"),
]


def _match(i, score=0.9):
    r = ROWS[i]
    return {"id": r[0], "score": score, "source": r[1], "section": r[2], "text": r[3]}


# ---- is_confident -------------------------------------------------------

def test_is_confident_empty():
    assert is_confident([]) is False


def test_is_confident_above_threshold():
    assert is_confident([{"score": RETRIEVAL_MIN_SCORE}]) is True


def test_is_confident_below_threshold():
    assert is_confident([{"score": RETRIEVAL_MIN_SCORE - 0.01}]) is False


def test_is_confident_uses_first_chunk_only():
    assert is_confident([{"score": 0.05}, {"score": 0.99}]) is False


# ---- context_chunks: komsu genisletme ---------------------------------

def test_neighbors_within_file():
    got = [r[0] for r in context_chunks([_match(1)], ROWS, window=1)]
    assert got == [0, 1, 2]


def test_neighbors_do_not_cross_file_boundary():
    # a.md son chunk'i (id 2); id 3 b.md -> baglama girmemeli
    got = [r[0] for r in context_chunks([_match(2)], ROWS, window=1)]
    assert got == [1, 2]


def test_window_zero_returns_only_matched():
    got = [r[0] for r in context_chunks([_match(1)], ROWS, window=0)]
    assert got == [1]


def test_overlapping_neighbors_deduped_and_ordered():
    got = [r[0] for r in context_chunks([_match(1), _match(2)], ROWS, window=1)]
    assert got == [0, 1, 2]  # tekrar yok


def test_result_ordered_by_id_across_separate_matches():
    got = [r[0] for r in context_chunks([_match(4), _match(0)], ROWS, window=1)]
    assert got == [0, 1, 3, 4]


def test_unknown_id_falls_back_to_chunk_itself():
    orphan = {"id": 99, "score": 0.9, "source": "z.md", "section": "Z", "text": "zz"}
    assert context_chunks([orphan], ROWS, window=1) == [(99, "z.md", "Z", "zz")]


def test_window_larger_than_file_clamps():
    got = [r[0] for r in context_chunks([_match(0)], ROWS, window=10)]
    assert got == [0, 1, 2]  # a.md ile sinirli


# ---- build_context ---------------------------------------------------

def test_build_context_format_and_neighbor_inclusion():
    ctx = build_context([_match(1)], ROWS, window=1)
    assert "[Source: a.md, Section: A0]" in ctx
    assert "[Source: a.md, Section: A2]" in ctx
    assert "reynolds number scaling" in ctx
    assert "b.md" not in ctx


# ---- get_top_chunks: gercek (kucuk) TF-IDF ---------------------------

@pytest.fixture
def tiny_index():
    rows = [
        (0, "a.md", "lift", "lift is generated by pressure difference over the wing"),
        (1, "b.md", "drag", "induced drag comes from wingtip vortices"),
        (2, "c.md", "stall", "stall happens past the critical angle of attack"),
    ]
    vec = TfidfVectorizer(stop_words="english")
    matrix = vec.fit_transform([r[3] for r in rows])
    return vec, matrix, rows


def test_get_top_chunks_ranks_relevant_first(tiny_index):
    vec, matrix, rows = tiny_index
    top = get_top_chunks("why does a wing stall at high angle of attack", vec, matrix, rows, k=3)
    assert top[0]["source"] == "c.md"
    assert top[0]["score"] >= top[1]["score"] >= top[2]["score"]


def test_get_top_chunks_includes_id_and_k_limit(tiny_index):
    vec, matrix, rows = tiny_index
    top = get_top_chunks("drag vortices", vec, matrix, rows, k=2)
    assert len(top) == 2
    assert all("id" in c for c in top)
