"""evaluate: icerik-kelime cikarimi, reddetme tespiti, grounding orani."""
from evaluate import _content_words, grounding_score, is_refusal

ROWS = [
    (0, "a.md", "Lift", "## Lift\nlift is generated by the pressure difference over the wing"),
    (1, "a.md", "Drag", "## Drag\ninduced drag is caused by wingtip vortices"),
]


def _match(i):
    r = ROWS[i]
    return {"id": r[0], "score": 0.9, "source": r[1], "section": r[2], "text": r[3]}


# ---- _content_words ------------------------------------------------

def test_content_words_drops_stopwords_and_short_tokens():
    words = _content_words("The wing generates LIFT at a high AoA")
    assert "wing" in words and "generates" in words and "lift" in words
    assert "the" not in words and "at" not in words and "a" not in words


# ---- is_refusal --------------------------------------------------

def test_is_refusal_true_when_leads_with_phrase():
    assert is_refusal("I don't have that information in my knowledge base.") is True


def test_is_refusal_false_when_disclaimer_only_trails_a_real_answer():
    ans = ("A stall occurs when the wing exceeds its critical angle of attack "
           "and lift drops sharply. I don't have that information.")
    assert is_refusal(ans) is False


def test_is_refusal_false_for_normal_answer():
    assert is_refusal("Static stability is the initial tendency to return to trim.") is False


# ---- grounding_score -------------------------------------------

def test_grounding_high_when_answer_drawn_from_context():
    ans = "Lift comes from a pressure difference over the wing."
    score = grounding_score(ans, [_match(0)], "how is lift generated", ROWS)
    assert score > 0.5


def test_grounding_low_when_answer_is_off_topic():
    ans = "Quantum chromodynamics describes gluon color confinement entirely."
    score = grounding_score(ans, [_match(0)], "how is lift generated", ROWS)
    assert score < 0.3


def test_grounding_degenerate_answer_equals_question():
    score = grounding_score("how is lift generated", [_match(0)], "how is lift generated", ROWS)
    assert score == 1.0
